galaxy_info:
  role_name: caac_export
  author: clickopstocaac
  description: Export AAP UI objects to config-as-code using infra.aap_configuration_extended
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - all

dependencies: []
